# Generated by Django 4.2.4 on 2023-09-17 18:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images/')),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('listingType', models.CharField(max_length=50)),
                ('dateCreated', models.DateField(default=datetime.date.today)),
                ('dateAvailable', models.DateField()),
                ('price', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=20)),
                ('contacts', models.CharField(max_length=300)),
                ('listingList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.listinglist')),
            ],
        ),
    ]
